#!/bin/bash

echo "Checking presence of Python..."
check=`dpkg -l | grep -i -e "^ii[ \t][ \t]*python[ \t][ \t]*"`
if [ -z "$check" ]; then
  echo "Please, install Python in order to use this program:"
  echo "sudo apt-get install python"
  sudo apt-get install python
  if [ $? -ne 0 ]; then echo 'FAIL'; fi
else
  echo "OK"
fi

echo "Checking presence of GData..."
check=`dpkg -l | grep -i -e "^ii[ \t][ \t]*python-gdata[ \t][ \t]*"`
if [ -z "$check" ]; then
  echo "Please, install Python GData library in order to use this program:"
  echo "sudo apt-get install python-gdata"
  sudo apt-get install python-gdata
  if [ $? -ne 0 ]; then echo 'FAIL'; fi
else
  echo "OK"
fi

echo "Checking presence of ExifTool..."
check=`dpkg -l | grep -i -e "^ii[ \t][ \t]*libimage-exiftool-perl[ \t][ \t]*"`
if [ -z "$check" ]; then
  echo "Please, install ExifTool in order to use this program:"
  echo "sudo apt-get install libimage-exiftool-perl"
  sudo apt-get install libimage-exiftool-perl
  if [ $? -ne 0 ]; then echo 'FAIL'; fi
else
  echo "OK"
fi

echo "Checking presence of ImageMagick..."
check=`dpkg -l | grep -i -e "^ii[ \t][ \t]*imagemagick[ \t][ \t]*"`
if [ -z "$check" ]; then
  echo "Please, install ImageMagick in order to use this program:"
  echo "sudo apt-get install imagemagick"
  sudo apt-get install imagemagick
  if [ $? -ne 0 ]; then echo 'FAIL'; fi
else
  echo "OK"
fi

